/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ykinptyiytyenumlowaa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlraW5wdHlpeXR5ZW51bWxvd2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNDU1NzgsImV4cCI6MjA3NzcyMTU3OH0.6-eGV43wal_Wcnh1J6YN9fy07ny8_SXsc68Y-eVAd6k"